pipeline {
    agent any

    stages {
        stage('Running collection') {
            steps {
                sh 'newman --version'
                sh 'newman run https://api.postman.com/collections/23078815-99d7721e-2413-458f-8105-32ef9abb6981?apikey=PMAK-65e97742287b4b000134815c-833422d96aa4d107da31598fa15548ae63 --disable-unicode --reporters cli,htmlextra,junit --reporter-htmlextra-export newman/report.html --reporter-junit-export newman/report.xml'
            }
        }
    }
        post {
        always {
            publishHTML target: [
                reportName: 'Newman',
                reportDir: 'newman',
                reportFiles: 'report.html',
                reportTitles: 'Postman API tests',
                keepAll: true,
                alwaysLinkToLastBuild: true,
                allowMissing: false
            ]
            junit 'newman/report.xml'
        }
    }
    
}
